using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("SportsStore.WebUI")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("SportsStore.WebUI")]
[assembly: AssemblyCopyright("Copyright ©  2016")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("d7293728-f548-496c-8d60-455795635bb1")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Patch Version
//      Build (Generated by build tool and not maintained in VC)
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
// We keep the version we are developing proper here. The builds will change this and add build number
// Is there a better way?? 
[assembly: AssemblyVersion("1.0.8.0")]
[assembly: AssemblyInformationalVersion("1.0.8.0")]
[assembly: AssemblyFileVersion("1.0.8.0")]

